# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Prince/Documents/GitHub/MiniWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Prince/Documents/GitHub/MiniWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.2.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Prince/Documents/GitHub/MiniWorld/CMakeFiles /Users/Prince/Documents/GitHub/MiniWorld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Prince/Documents/GitHub/MiniWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MiniWorld

# Build rule for target.
MiniWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MiniWorld
.PHONY : MiniWorld

# fast build rule for target.
MiniWorld/fast:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/build
.PHONY : MiniWorld/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f deps/glfw/CMakeFiles/uninstall.dir/build.make deps/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f deps/glfw/src/CMakeFiles/glfw.dir/build.make deps/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

deps/glew/src/glew.o: deps/glew/src/glew.c.o
.PHONY : deps/glew/src/glew.o

# target to build an object file
deps/glew/src/glew.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/glew/src/glew.c.o
.PHONY : deps/glew/src/glew.c.o

deps/glew/src/glew.i: deps/glew/src/glew.c.i
.PHONY : deps/glew/src/glew.i

# target to preprocess a source file
deps/glew/src/glew.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/glew/src/glew.c.i
.PHONY : deps/glew/src/glew.c.i

deps/glew/src/glew.s: deps/glew/src/glew.c.s
.PHONY : deps/glew/src/glew.s

# target to generate assembly for a file
deps/glew/src/glew.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/glew/src/glew.c.s
.PHONY : deps/glew/src/glew.c.s

deps/lodepng/lodepng.o: deps/lodepng/lodepng.c.o
.PHONY : deps/lodepng/lodepng.o

# target to build an object file
deps/lodepng/lodepng.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/lodepng/lodepng.c.o
.PHONY : deps/lodepng/lodepng.c.o

deps/lodepng/lodepng.i: deps/lodepng/lodepng.c.i
.PHONY : deps/lodepng/lodepng.i

# target to preprocess a source file
deps/lodepng/lodepng.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/lodepng/lodepng.c.i
.PHONY : deps/lodepng/lodepng.c.i

deps/lodepng/lodepng.s: deps/lodepng/lodepng.c.s
.PHONY : deps/lodepng/lodepng.s

# target to generate assembly for a file
deps/lodepng/lodepng.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/lodepng/lodepng.c.s
.PHONY : deps/lodepng/lodepng.c.s

deps/noise/noise.o: deps/noise/noise.c.o
.PHONY : deps/noise/noise.o

# target to build an object file
deps/noise/noise.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/noise/noise.c.o
.PHONY : deps/noise/noise.c.o

deps/noise/noise.i: deps/noise/noise.c.i
.PHONY : deps/noise/noise.i

# target to preprocess a source file
deps/noise/noise.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/noise/noise.c.i
.PHONY : deps/noise/noise.c.i

deps/noise/noise.s: deps/noise/noise.c.s
.PHONY : deps/noise/noise.s

# target to generate assembly for a file
deps/noise/noise.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/noise/noise.c.s
.PHONY : deps/noise/noise.c.s

deps/sqlite/sqlite3.o: deps/sqlite/sqlite3.c.o
.PHONY : deps/sqlite/sqlite3.o

# target to build an object file
deps/sqlite/sqlite3.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/sqlite/sqlite3.c.o
.PHONY : deps/sqlite/sqlite3.c.o

deps/sqlite/sqlite3.i: deps/sqlite/sqlite3.c.i
.PHONY : deps/sqlite/sqlite3.i

# target to preprocess a source file
deps/sqlite/sqlite3.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/sqlite/sqlite3.c.i
.PHONY : deps/sqlite/sqlite3.c.i

deps/sqlite/sqlite3.s: deps/sqlite/sqlite3.c.s
.PHONY : deps/sqlite/sqlite3.s

# target to generate assembly for a file
deps/sqlite/sqlite3.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/sqlite/sqlite3.c.s
.PHONY : deps/sqlite/sqlite3.c.s

deps/tinycthread/tinycthread.o: deps/tinycthread/tinycthread.c.o
.PHONY : deps/tinycthread/tinycthread.o

# target to build an object file
deps/tinycthread/tinycthread.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/tinycthread/tinycthread.c.o
.PHONY : deps/tinycthread/tinycthread.c.o

deps/tinycthread/tinycthread.i: deps/tinycthread/tinycthread.c.i
.PHONY : deps/tinycthread/tinycthread.i

# target to preprocess a source file
deps/tinycthread/tinycthread.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/tinycthread/tinycthread.c.i
.PHONY : deps/tinycthread/tinycthread.c.i

deps/tinycthread/tinycthread.s: deps/tinycthread/tinycthread.c.s
.PHONY : deps/tinycthread/tinycthread.s

# target to generate assembly for a file
deps/tinycthread/tinycthread.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/deps/tinycthread/tinycthread.c.s
.PHONY : deps/tinycthread/tinycthread.c.s

src/cube.o: src/cube.c.o
.PHONY : src/cube.o

# target to build an object file
src/cube.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/cube.c.o
.PHONY : src/cube.c.o

src/cube.i: src/cube.c.i
.PHONY : src/cube.i

# target to preprocess a source file
src/cube.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/cube.c.i
.PHONY : src/cube.c.i

src/cube.s: src/cube.c.s
.PHONY : src/cube.s

# target to generate assembly for a file
src/cube.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/cube.c.s
.PHONY : src/cube.c.s

src/db.o: src/db.c.o
.PHONY : src/db.o

# target to build an object file
src/db.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/db.c.o
.PHONY : src/db.c.o

src/db.i: src/db.c.i
.PHONY : src/db.i

# target to preprocess a source file
src/db.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/db.c.i
.PHONY : src/db.c.i

src/db.s: src/db.c.s
.PHONY : src/db.s

# target to generate assembly for a file
src/db.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/db.c.s
.PHONY : src/db.c.s

src/item.o: src/item.c.o
.PHONY : src/item.o

# target to build an object file
src/item.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/item.c.o
.PHONY : src/item.c.o

src/item.i: src/item.c.i
.PHONY : src/item.i

# target to preprocess a source file
src/item.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/item.c.i
.PHONY : src/item.c.i

src/item.s: src/item.c.s
.PHONY : src/item.s

# target to generate assembly for a file
src/item.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/item.c.s
.PHONY : src/item.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/main.c.s
.PHONY : src/main.c.s

src/map.o: src/map.c.o
.PHONY : src/map.o

# target to build an object file
src/map.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/map.c.o
.PHONY : src/map.c.o

src/map.i: src/map.c.i
.PHONY : src/map.i

# target to preprocess a source file
src/map.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/map.c.i
.PHONY : src/map.c.i

src/map.s: src/map.c.s
.PHONY : src/map.s

# target to generate assembly for a file
src/map.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/map.c.s
.PHONY : src/map.c.s

src/matrix.o: src/matrix.c.o
.PHONY : src/matrix.o

# target to build an object file
src/matrix.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/matrix.c.o
.PHONY : src/matrix.c.o

src/matrix.i: src/matrix.c.i
.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/matrix.c.i
.PHONY : src/matrix.c.i

src/matrix.s: src/matrix.c.s
.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/matrix.c.s
.PHONY : src/matrix.c.s

src/ring.o: src/ring.c.o
.PHONY : src/ring.o

# target to build an object file
src/ring.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/ring.c.o
.PHONY : src/ring.c.o

src/ring.i: src/ring.c.i
.PHONY : src/ring.i

# target to preprocess a source file
src/ring.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/ring.c.i
.PHONY : src/ring.c.i

src/ring.s: src/ring.c.s
.PHONY : src/ring.s

# target to generate assembly for a file
src/ring.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/ring.c.s
.PHONY : src/ring.c.s

src/sign.o: src/sign.c.o
.PHONY : src/sign.o

# target to build an object file
src/sign.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/sign.c.o
.PHONY : src/sign.c.o

src/sign.i: src/sign.c.i
.PHONY : src/sign.i

# target to preprocess a source file
src/sign.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/sign.c.i
.PHONY : src/sign.c.i

src/sign.s: src/sign.c.s
.PHONY : src/sign.s

# target to generate assembly for a file
src/sign.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/sign.c.s
.PHONY : src/sign.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/util.c.s
.PHONY : src/util.c.s

src/world.o: src/world.c.o
.PHONY : src/world.o

# target to build an object file
src/world.c.o:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/world.c.o
.PHONY : src/world.c.o

src/world.i: src/world.c.i
.PHONY : src/world.i

# target to preprocess a source file
src/world.c.i:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/world.c.i
.PHONY : src/world.c.i

src/world.s: src/world.c.s
.PHONY : src/world.s

# target to generate assembly for a file
src/world.c.s:
	$(MAKE) -f CMakeFiles/MiniWorld.dir/build.make CMakeFiles/MiniWorld.dir/src/world.c.s
.PHONY : src/world.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... MiniWorld"
	@echo "... install/local"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... deps/glew/src/glew.o"
	@echo "... deps/glew/src/glew.i"
	@echo "... deps/glew/src/glew.s"
	@echo "... deps/lodepng/lodepng.o"
	@echo "... deps/lodepng/lodepng.i"
	@echo "... deps/lodepng/lodepng.s"
	@echo "... deps/noise/noise.o"
	@echo "... deps/noise/noise.i"
	@echo "... deps/noise/noise.s"
	@echo "... deps/sqlite/sqlite3.o"
	@echo "... deps/sqlite/sqlite3.i"
	@echo "... deps/sqlite/sqlite3.s"
	@echo "... deps/tinycthread/tinycthread.o"
	@echo "... deps/tinycthread/tinycthread.i"
	@echo "... deps/tinycthread/tinycthread.s"
	@echo "... src/cube.o"
	@echo "... src/cube.i"
	@echo "... src/cube.s"
	@echo "... src/db.o"
	@echo "... src/db.i"
	@echo "... src/db.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... src/ring.o"
	@echo "... src/ring.i"
	@echo "... src/ring.s"
	@echo "... src/sign.o"
	@echo "... src/sign.i"
	@echo "... src/sign.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

